### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by Breeze-Zero** [Const-me/Whisper#11]
My laptop is i7+RXT3050, and when I use the software, the GPU is not working, while Intel's integrated graphics are full power
![1675086952342](https://user-images.githubusercontent.com/78247190/215496719-beb328b4-5f18-423b-a7b3-eed418ee72f0.png)

**Comment by dkakaie** [comment]
You should manually set your preferred GPU per app in this case. On Windows 11 you can go to Settings>System>Display>Graphics. Click browse, select you application, Whisper in this case, and finally select high performance profile which sets it to your dedicated GPU.
![Untitled](https://user-images.githubusercontent.com/31028960/215567883-3cdaf854-714e-45a1-ba62-75560dc56ac0.png)

**Comment by Const-me** [comment]
@Breeze-Zero Should be fixed in version 1.6.1
