### ISSUE TITLE
Problem when using large-v2

### ISSUE THREAD

**Issue by Dragoy** [Const-me/Whisper#114]
When using the latest version of the model, it does not transcribes Korean subtitles, but makes meaningless output to the console 

![7B17C42D-FDC9-47FC-BCDA-7676C1CC2D0D](https://github.com/Const-me/Whisper/assets/4968313/c625cfdf-724d-4007-8ad5-a8091f8a0bc4)

**Comment by FerLuisxd** [comment]
Where did you get "large-v2"?

So we can replicate this issue

**Comment by Dragoy** [comment]
I found him here: https://huggingface.co/datasets/ggerganov/whisper.cpp/blob/main/ggml-large.bin
I also think it could work with this: https://huggingface.co/guillaumekln/faster-whisper-large-v2/blob/main/model.bin
