### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by bastauno** [Const-me/Whisper#12]
Thanks for this very useful application. Do you think it's possible to add the ability to translate into other languages ​​than English? In my case Italian. Ciao

**Comment by Const-me** [comment]
Possible, but that would be non-trivial amount of work.
Most importantly, I don’t even speak Italian, I can’t support a language I don’t speak.

**Comment by bastauno** [comment]
I explained myself badly, I use the automatic translator... I wanted to know if Whisper can translate an audio into other languages ​​than English.

**Comment by Const-me** [comment]
@bastauno In their upstream repository, OpenAI wrote they have not trained their language model for that use case: https://github.com/openai/whisper/discussions/649
I have tried processing some English audio clips with Language=Serbian and “Transcribe” button, but the results were pretty much garbage.
I think the answer to your question “no, it can’t do that”

**Comment by bastauno** [comment]
Thank you. Your application is very useful.
