### ISSUE TITLE
How can i build target .net framework 4.8

### ISSUE THREAD

**Issue by dominota** [Const-me/Whisper#120]
Hi,

I want to build Whisper for .Net Framework 4.8? Is there any guides ?

Thanks

**Comment by Const-me** [comment]
The current version of the library only supports modern .NET.

I don’t have guides, but I have an example you can rework into a .NET 4 library. The example is the [PowerShell module](https://github.com/Const-me/Whisper/tree/master/WhisperPS).
That project targets the PowerShell which is included in Windows, therefore uses .NET Framework 4.7.2.
Starting from that project, it shouldn’t be hard to implement the legacy .NET projection of the C++ DLL.
