### ISSUE TITLE
Do you have any plan to add translate feature?

### ISSUE THREAD

**Issue by bluenlive** [Const-me/Whisper#127]
Thanks for the great program.
I use Intel Arc on Windows, so Const-me/Whisper seems to be the only service I can use for now.

Do you have any plans to implement a translation feature?
Now we can only translate to English, but it would be nice to have the ability to translate from English to other languages.

**Comment by albino1** [comment]
None of the Whisper models support translating from English to other languages.  Maybe one day in the future, but it's not something that can just be added.

**Comment by bluenlive** [comment]
Ok. Thanks.
I should wait.
