### ISSUE TITLE
MicrophoneCS Example

### ISSUE THREAD

**Issue by Nuked88** [Const-me/Whisper#131]
Sooo, i tried to use the MicrophoneCS example, at the first it was giving to me error of minDuration and then maxDuration with an invalid value (0) so i setted them 5.0f and 15.0f manually after line 42 of MicrophoneCS.cs. Then i canged the index of the capture devices on the right device, but i really not understand where is the point where the model is analyzing the audio giving me the transcript, since for what i'm seeing is just telling me when i'm speaking and when it should trascribe (with CaptureStatusChanged callback) but it seems to never call the other callback. So i don't know that to do :(

**Comment by Captain-FLAM** [comment]
I was stuck on it too, then I found the solution (for my own purpose) :

**Line 37 :**
```
sCaptureParams cp = new sCaptureParams();

// Captain FLAM
// ********************
cp.minDuration = 7.0f;         // 7 seconds
cp.maxDuration = 11.0f;        // 11 seconds
cp.dropStartSilence = 0.25f;   // 250 ms
cp.pauseDuration = 0.333f;     // 333 ms
cp.flags = eCaptureFlags.None;

eGpuModelFlags flags = eGpuModelFlags.None;
eModelImplementation implementation = eModelImplementation.GPU;

// ********************
```

Then I set my good GPU manually (that was the problem : It doesn't work with the GPU of HD Graphics inside Intel processor) !

**Line 56 :**
```
using iModel model = Library.loadModel( cla.model, flags, "NVIDIA GeForce GTX 1650", implementation);
```

**Comment by Nuked88** [comment]
Nice, i'll try that! Thanks!

**Comment by Const-me** [comment]
Fixed in master.

`sCaptureParams` structure has a constructor with `bool` argument which sets reasonable default values in that structure. Structures in C# didn’t support default values until language version 10.0. That source file is shared between .NET 6.0 and .NET 4.7.2 in PowerShell, so the feature unavailable.

**Comment by emcodem** [comment]
thanks for leaving this open so i found it quickly. I had the minduration exception, then read this thread, updated to latest master and built - voila, problem is gone
