### ISSUE TITLE
Support .webm and .weba

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [Const-me/Whisper#138]
Type mutilmedia seems not includes `.webm`, also the `.weba`.

**Comment by emcodem** [comment]
you can install corresponding directshow filters i guess. From this libraries perspective it would be better to support being fed from stdin so we can easly support virtually all audio codecs and sources out there.

**Comment by natural-harmonia-gropius** [comment]
webm is strictly mkv, that vp9 and opus codeces are already supported. I can simply remux it to mkv to get supports.

**Comment by tigros** [comment]
You can use [Whisperer](https://github.com/tigros/Whisperer) for such problems, everything gets converted to .wav by ffmpeg first.
