### ISSUE TITLE
Add option for batch transcribing multiple files?

### ISSUE THREAD

**Issue by zelenooki87** [Const-me/Whisper#14]
Hi.
Thanks for the great work, 
GPU acceleration extremely faster decodes text, than official ggerganov project which doesnt support gpu yet.
Could you please implement option for multiple subtitle generation, to program allow batch import files?
Thank you very much in advance!

**Comment by Const-me** [comment]
The latest 1.7 release has one more binary there, `main.exe` in the `cli.zip` archive.

That application is a command-line tool which can be used for batch processing.

To print command-line usage help, run `main.exe --help`

Example which transcribes 2 files, and saves `*.txt` in the folder with the input audio files:

`main.exe --model D:\Data\Whisper\ggml-medium.bin --output-txt --no-timestamps C:\Temp\2remove\Whisper\columbia.wma C:\Temp\2remove\Whisper\jfk.wav`

**Comment by mathiasfoster** [comment]
I have a directory with many hundreds of audio files, it would be very laborious to specify each file in the command.
Can we have an option to specify a directory in the command, for all audio files within to be transcribed?

**Comment by tigros** [comment]
i'm definitely gonna upgrade my lil thingy to use this, https://github.com/tigros/Whisperer should be done soon.
