### ISSUE TITLE
Ability to capture audio from YouTube, twitch, etc.. and preform live transcription and translation

### ISSUE THREAD

**Issue by SumDevv** [Const-me/Whisper#141]
I think it would be neat to have the ability to transcribe audio coming from the web or desktop and display subtitles in real time, for example; say you were watching a twitch stream in a foreign language, having the ability to be able to display the translations as well as a save a transcript to disk.

**Comment by emcodem** [comment]
Functionality is already there, all you have to do is to route your sound to a microphone. I use VB-Audio Virutal Cable for such usecases.
