### ISSUE TITLE
Performance notes on AMD (RDNA2)

### ISSUE THREAD

**Issue by marcin-przywoski** [Const-me/Whisper#16]
Not really an issue but I'm giving my thoughts on RDNA2 performance. In short - It's great. On my 6900xt it looks around 7.7x realtime for the large model and for the medium one - 10.5x

**Comment by Const-me** [comment]
@marcin-przywoski There’s “advanced…” button on the first dialog.
The default values are “Wave64 shaders on AMD” and “Reshape on AMD”.
If you switch these settings to “Wave32, always” and “Don’t reshape tensors”, and press OK, will it become faster or slower on your computer?
![advanced](https://user-images.githubusercontent.com/925112/217501405-bef08876-2849-49af-ad5b-57684fb5eaf1.png)

**Comment by marcin-przywoski** [comment]
@Const-me It was slower but not a lot, from 7.7 down to 7.35 on large model

**Comment by Const-me** [comment]
@marcin-przywoski Thanks for that test.
I have implemented these AMD-specific optimizations for the integrated Vega GPUs. By default, for users who never click that advanced button, these optimizations are applied when vendor ID of the graphics card says `AMD = 0x1002`
Good news they didn’t make things worse on your GPU, which is very different from the low-power CPU-integrated AMD GPUs I have tested here.

**Comment by pleonard212** [comment]
Just another data point: the Intel Hades Canyon NUC, which uses a Radeon RX Vega M GH, is slowed down by these optimizations, following the same test procedure as above:

- 1.75x speed **with** AMD optimizations
-  2.34x speed **without** 

 `large_v2` model, set to English, audio file of just under five minutes.

**Comment by Const-me** [comment]
@pleonard212 Interesting. I have no idea why that is.
At least you have that “advanced…” button, and the corresponding bits in the `eGpuModelFlags` enum when consuming the library programmatically.
If you want to optimize the performance on your particular GPU, start with the magic numbers in the expensive compute shaders. See [that commit](https://github.com/Const-me/Whisper/commit/e78815de53005336c3746bcd85c2e789a43f1b94) for the example of such change.
