### ISSUE TITLE
Description is misleading

### ISSUE THREAD

**Issue by tom-huntington** [Const-me/Whisper#160]
*GPGPU inference* sounds like this is gpu accelerated.

But Whisper.cpp is a SIMD accelerated cpu model. I think the description should read

> High-performance SIMD inference of OpenAI's Whisper automatic speech recognition (ASR) model

**Comment by tom-huntington** [comment]
Woops, you ported the SIMD to DirectCompute

**Comment by wenchaoliu-93** [comment]
Not sure what you mean. This Windows executable uses GPU, mainly.
