### ISSUE TITLE
Sample code for WhisperNet?

### ISSUE THREAD

**Issue by ihavegoodnameiscool** [Const-me/Whisper#167]
i have figured out how to create context and load the model, but am having trouble transcribing a file stream.

**Comment by art3xias23** [comment]
Would have been nice if you had posted your outcome @ihavegoodnameiscool

**Comment by ihavegoodnameiscool** [comment]
Go into the examples folder, i didnt see it before https://github.com/Const-me/Whisper/tree/master/Examples
