### ISSUE TITLE
Provide raw audio samples from .NET

### ISSUE THREAD

**Issue by dkakaie** [Const-me/Whisper#17]
Not really an issuel; merely curious.
One if MF helpers simply accepts file path, however providing audio samples directly would also be nice, like when recording audio from .NET. Is it planned?

**Comment by Const-me** [comment]
You can already do that with the current version of the library.
[Example.](https://gist.github.com/Const-me/082c8d96eb10b76058c5dd9c68b5bfe1)

P.S. Note that resampling audio is hard. If your source can’t deliver 16 kHz sample rate, you gonna have hard time implementing good audio resampling in C#. My C++ code doesn’t do that either, the resampling is implemented by Microsoft deep inside their media foundation framework.
