### ISSUE TITLE
I want to process multiple files with WhisperDesktop

### ISSUE THREAD

**Issue by kbuwel** [Const-me/Whisper#174]
There are numerous audio files in the folder.
It takes a long time and it is difficult to convert the entire file.
It would be nice to have the ability to specify a folder within WhisperDesktop and then select all files in that folder for processing.
It would be nice if the corresponding folder and recognized files were recorded in the recognition results.
For example, it would be good to write it like this:
a
a.wav
hi

**Comment by RickArcher108** [comment]
Use Whisperer. Works like a charm:

Download from:

https://github.com/tigros/Whisperer/releases/download/2.8/Whisperer.zip
then you would download ggml-large.bin<https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-large.bin> from https://huggingface.co/ggerganov/whisper.cpp/tree/main


Rick Archer
Buddha at the Gas Pump
https://batgap.com
***@***.***


From: kbuwel ***@***.***>
Sent: Monday, September 18, 2023 12:00 PM
To: Const-me/Whisper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Const-me/Whisper] I want to process multiple files with WhisperDesktop (Issue #174)


There are numerous audio files in the folder.
It takes a long time and it is difficult to convert the entire file.
It would be nice to have the ability to specify a folder within WhisperDesktop and then select all files in that folder for processing.
It would be nice if the corresponding folder and recognized files were recorded in the recognition results.
For example, it would be good to write it like this:
a
a.wav
hi

**Comment by NikosDi** [comment]
It's better not to give the link of specific releases like the one above.
You linked v2.8 which is the previous one than the current.

The current release is here:
https://github.com/tigros/Whisperer/releases
