### ISSUE TITLE
Support multiple simultaneous outputs

### ISSUE THREAD

**Issue by savchenko** [Const-me/Whisper#19]
Would be good to have support of simultaneous `-otxt`, `-ovtt` and `-osrt` as well as the regular text.
It is possible with the original CLI whisper.

**Comment by Const-me** [comment]
@savchenko  [Release 1.7](https://github.com/Const-me/Whisper/releases/tag/1.7.0) has a command-line version, `main.exe` inside `cli.zip` archive. You should be able to use that binary to achieve that with my implementation. Example in https://github.com/Const-me/Whisper/issues/14

I don’t want to support the feature you have suggested in the GUI app.

I think most people only need 1 output format. I could adjust the GUI to multi-select output formats and ask users for unique output path for each selected output format. That’s going to be a lot of controls in that dialog. For people who only need a single format, the software will become harder to use.
