### ISSUE TITLE
Where are the releases? 

### ISSUE THREAD

**Issue by RYucel** [Const-me/Whisper#2]
Sorry to ask but could not find releases link to download for windows executable. Is there any link to it on read.me?

**Comment by RYucel** [comment]
I built it as instructed. Worked like a charm. Thank you for this wonderful solution

**Comment by Const-me** [comment]
@RYucel  On the right side of the main page of the repository, there’s a **Releases** link, links there: https://github.com/Const-me/Whisper/releases

So far, the latest one is 1.1.

**Comment by RYucel** [comment]
Thank you. Very good project btw
