### ISSUE TITLE
Building error: shaderData-Release.inl

### ISSUE THREAD

**Issue by sigurd-dev** [Const-me/Whisper#21]

**Comment by sigurd-dev** [comment]
I get a error while building: Error	C1083	Cannot open include file: 'shaderData-Release.inl': No such file or directory, what am I missing?

**Comment by Const-me** [comment]
@sigurd-dev You’re missing a step “Build **and run** CompressShaders C# project, in the Tools subfolder of the solution.”

**Comment by sigurd-dev** [comment]
Thank you for promp answer, this pointed me in a right direction.
