### ISSUE TITLE
a Exception about "shaderData-Debug.inl":No such file or directory

### ISSUE THREAD

**Issue by wangtao7611** [Const-me/Whisper#210]
hello, a exception said "shaderData-Debug.inl":No such file or directory , and another is Whisper.dll can't copy  when i compile the project.
can you help me?

**Comment by Const-me** [comment]
@wangtao7611 Just follow [the instructions](https://github.com/Const-me/Whisper?tab=readme-ov-file#build-instructions), these C++ source files are generated by step 4.

**Comment by wangtao7611** [comment]
thanks, it's run.
