### ISSUE TITLE
Cannot locate literal strings that are output during detection/transcription

### ISSUE THREAD

**Issue by smbika007** [Const-me/Whisper#27]
I notice that sometimes the following strings (amongst others) will appear while it's transcribing:

[BLANK_AUDIO]
[MUSIC]
[VIDEO STARTING]
etc.

I did a search for these strings and they do not appear to be in the code base. I extended the search to my C: drive and could not find them anywhere. My search facility may have skipped some files due to format (dlls and exes)...

Can you tell me where they originate from?

Thanks!

**Comment by dkakaie** [comment]
They are predicted by the model just like other transcriptions.

**Comment by smbika007** [comment]
Doh! Thanks!
