### ISSUE TITLE
"Hybrid" mode is not working

### ISSUE THREAD

**Issue by RYucel** [Const-me/Whisper#3]
Other than "GPU" mode, I could not run other modes such as "Hybrid". Throw error as missing some "DLLs" for both other two modes. How can we fix this and what are the main purposes of these modes as could not find any explanation for them? By the way, very good project and results are great!

**Comment by Const-me** [comment]
> How can we fix this

To enable these modes, you gonna have to rebuild `Whisper.dll`.
Edit `Whisper/stdafx.h` header, change the following value from 0 to 1 to enable the hybrid version:
```
#define BUILD_HYBRID_VERSION 0
```
Change the following value from 0 to 1 to enable the reference version:
```
#define BUILD_BOTH_VERSIONS 0
```
> what are the main purposes of these modes

I used them for testing during development.

The hybrid model uses DirectCompute for encode and decodes on CPU.

The reference implementation uses the original GGML C code to run the model. It’s also fairly limited, the current examples won’t work with that model, except the C# TranscribeCS example if you change [the streamAudio flag](https://github.com/Const-me/Whisper/blob/1.1.0/Examples/TranscribeCS/TranscribeCS.cs#L7) to false
