### ISSUE TITLE
transcription does not terminate at eof 

### ISSUE THREAD

**Issue by datenhain** [Const-me/Whisper#4]
first, thank you for your great work.
In certain cases the transcription process does not terminate at the end of the file and does
not write to the txt/vtt/srt file. My testfile was a 48kHz/stereo/mp3 file. If I convert it to
16bit wav as expected by the original whisper.cpp it works fine.

**Comment by Const-me** [comment]
@datenhain [I’ve converted](https://u.pcloud.link/publink/show?code=XZB4P9VZPMU6e8hT3lkui7T8ASPujh5ySf9X) one of my test files to 48kHz mp3, but it worked fine on my computer.
Can you possibly share such an MP3 file?

**Comment by datenhain** [comment]
https://drive.google.com/file/d/1J32fNyidkfL3bIK5aLBrAs2Kazf8VsVN/view?usp=sharing

**Comment by Const-me** [comment]
@datenhain Please try the new version 1.3

**Comment by datenhain** [comment]
looking good :) thx a lot
