### ISSUE TITLE
feature request: Transcribe by different model one by one.

### ISSUE THREAD

**Issue by ivysrono** [Const-me/Whisper#40]
By tests, `ggml-medium.bin` and `ggml-large.bin` each have their own wins and losses.
So I'd like to get two output txt files just one click.

We can load 2 models at the same time.
Output to `filename-large.txt` and `filename-medium.txt` one by one.

**Comment by jaybinks** [comment]
Const-me's whisper.dll will allow you to do that , you will just need to wrap it with your own script , CLI or UI  to do what you want.

**Comment by Const-me** [comment]
@jaybinks I believe these advanced use cases are better handled with scripting, as opposed to over-complicated CLI or GUI.
For this reason, in version 1.10 I’ve implemented PowerShell 5.1 wrapper.
See [the readme](https://github.com/Const-me/Whisper/tree/master/WhisperPS).
