### ISSUE TITLE
Feature request: an option to save all formats

### ISSUE THREAD

**Issue by bilo1967** [Const-me/Whisper#45]
It would be nice to have an option to save all output formats at once (txt with timestamps and various subtitle formats) instead of just one at a time.

**Comment by Const-me** [comment]
@bilo1967 I don’t want to overwhelm users with complicated GUI.
I believe these advanced use cases are better handled with scripting, so I’ve implemented the PowerShell wrappers.
See [the readme](https://github.com/Const-me/Whisper/tree/master/WhisperPS).
