### ISSUE TITLE
Request: Include binary for whispercpp beta v1.1.0

### ISSUE THREAD

**Issue by Topping1** [Const-me/Whisper#6]
Great work! I did not expect this program to be so fast. One thing that can make it better: to include an additional WhisperDesktop.exe with the updates in the official whispercpp beta v1.1.0. This beta improves the transcription of files that previously got stuck in the same sentence. I hope that this is a reasonable request.

**Comment by Const-me** [comment]
@Topping1 Could you please upload or link an audio file I can use to reproduce that issue on my computer?

**Comment by Topping1** [comment]
I could not find the file again yet, but in the meantime I have found an audio in french that freezes the program about 5 minutes into the transcription [link](https://youtu.be/Jll6mMcnJUo)

**Comment by Const-me** [comment]
@Topping1 Sadly, this doesn’t happen on my computer.
[Uploaded the logs](http://const.me/tmp/whisper-french.zip).

How did you get the file? I’ve used “YouTube Downloader” browser addon, selected the “MP4 HD 1280X720” option.
What’s your GPU model?

**Comment by Topping1** [comment]
I used yt-dlp for downloading the audio directly to an mp3 file. I'm using a Quadro P1000 (4gb vram)

**Comment by Const-me** [comment]
@Topping1 Does it happen with the latest version, 1.6.1?

**Comment by Topping1** [comment]
@Const-me version 1.6.1 fixes the issue for me. Thanks!
