### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by adamreed90** [Const-me/Whisper#71]
Hello! 

I would love to contribute to making this work for Linux, but I am a bit of a novice when it comes to GPU interaction, if you have any suggestions of where to start, that would be great 👍

**Comment by Const-me** [comment]
@adamreed90 Yeah, currently the best option is Wine. If you want to port to Linux, that going to require a lot of work.

A hard way is replacing D3D11 with [DiligentEngine](https://github.com/DiligentGraphics/DiligentEngine), and Media Foundation with [ffmpeg](https://ffmpeg.org/) or [gstreamer](https://gstreamer.freedesktop.org/). Despite the name, Diligent Engine is not actually an engine, it’s a GPU abstraction library. On Linux it can run on top of Vulkan, and it can directly consume HLSL compute shaders.

An easier way is Winelib. I don’t have any experience with that tool, but in [user’s guide](https://wiki.winehq.org/Winelib_User's_Guide) they wrote they can compile Windows C++ code to Linux.
