### ISSUE TITLE
[Feature] Use Tensor Cores from Nvidia RTX cards

### ISSUE THREAD

**Issue by PriNova** [Const-me/Whisper#75]
I don't know if this would increase the performance. Also I'm not familiar with the Nvidia tensor core library nor the cudnn.

This is only a feature request, if it makes sense or would really bring performance increases. 
I have the RTX 3060 at home as dGPU in my laptop.

**Comment by Const-me** [comment]
@PriNova I can’t possibly do that because I don’t have an RTX card.
Also, based on my tests, the performance bottleneck appears to be VRAM bandwidth, not computations. Faster instructions to multiply these tensors probably not going to help.
