### ISSUE TITLE
enabling BUILD_BOTH_VERSIONS no longer builds.

### ISSUE THREAD

**Issue by philipag** [Const-me/Whisper#77]
BTW, even though Whisper.cpp might perform worse than shader based decoding, it is still worth enabling both since then one can use the CPU and GPU in parallel, thereby almost doubling performance...

**Comment by Const-me** [comment]
@philipag The compilation errors should be fixed now.
However, I stopped testing that thing (reference CPU implementation) couple months ago, no idea whether it still works or not.
