### ISSUE TITLE
Non-deterministic output regarding hyphenation

### ISSUE THREAD

**Issue by NWoodsman** [Const-me/Whisper#8]
I transcribed a file and the result included hyphenation. After review of the transcription, it's apparent that hyphens indicate change in speaker. Somehow the model is able to distinguish different voices and separate the back-and-forth of conversation into statements that start with -.

I transcribed a different file, and the result did not have hyphenation. 

It's unclear why I got hyphenation in some files, but not others.

**Comment by Const-me** [comment]
@NWoodsman  I’m not sure how I can help with that. I know very little about machine learning.

From my perspective, this library contains 50% magic, 15% audio signal processing like [Fourier transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform), and 35% [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) routines ported from C++ to HLSL and optimized for performance on GPUs.
I don’t really know how specifically the library produces text from speech, nor why it’s non-deterministic.

Still, if you upload or link the audio, I can at least compare with the reference versions. If I’ll find out there’s a bug in my implementation, then I might be able to fix. However, if the original version will demonstrate same behavior as my version, I won’t be able to do much to address the issue.

**Comment by dkakaie** [comment]
Whisper is mostly trained with data from YouTube and corresponding subtitles if I remember correctly. Hyphens were used to indicate change of speaker thus learned by the model during training. I don't think one can stop the model predicting that unless original data is wiped clean and re-trained, which is not going to happen.

**Comment by NWoodsman** [comment]
I originally thought the issue might have been caused by a baked-in parameter. It appears there are ongoing discussions regarding diarization on the main Whisper github page. At any rate, this thread is not applicable to Const-me's Whisper implementation.
