### ISSUE TITLE
No WhisperDesktop.exe in the extracted file folder 

### ISSUE THREAD

**Issue by ArthurMY** [Const-me/Whisper#90]
After download and extract the file, I couldn't found the WhisperDesktop.exe

**Comment by albino1** [comment]
Are you downloading WhisperDesktop.zip from the Releases page?

https://github.com/Const-me/Whisper/releases/tag/1.11.0

**Comment by ArthurMY** [comment]
I guess i downloaded the worng file, fixed it now. Thanks a lot.
