### ISSUE TITLE
Error loading the model 

### ISSUE THREAD

**Issue by korp-2** [Const-me/Whisper#92]
![image](https://user-images.githubusercontent.com/61874370/232176503-92546a4b-fc5a-4be5-96ba-63406de25ee8.png)
![image](https://user-images.githubusercontent.com/61874370/232176533-3d890bb1-3b13-4b02-8f9c-578a41f4d1af.png)
CPU Intel Core i5 2500 and GeForce GTX 970, Windows 10 x64
What is a error?

**Comment by Const-me** [comment]
Your processor is too old, it lacks [F16C](https://en.wikipedia.org/wiki/F16C#CPUs_with_F16C) instructions.
It’s not supported by the library. The requirement is [documented](https://github.com/Const-me/Whisper#features) in the readme.

**Comment by emaginsf** [comment]
I'm getting same error with Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   RAM 16.0 GB
Online reference shows F16C is supported https://www.cpu-world.com/cgi-bin/CPUID.pl?CPUID=74294



Any suggestions?

![gpu](https://github.com/Const-me/Whisper/assets/161665412/101296e9-1ee9-4bcd-a404-e040be3cac21)
![gpi2](https://github.com/Const-me/Whisper/assets/161665412/0a436cab-0014-4892-8dc6-e8819feed5f4)

**Comment by LdotJdot** [comment]
> I'm getting same error with Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz RAM 16.0 GB Online reference shows F16C is supported https://www.cpu-world.com/cgi-bin/CPUID.pl?CPUID=74294
> 
> Any suggestions?
> 
> ![gpu](https://private-user-images.githubusercontent.com/161665412/335764979-101296e9-1ee9-4bcd-a404-e040be3cac21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjg5NDAsIm5iZiI6MTczMjA2ODY0MCwicGF0aCI6Ii8xNjE2NjU0MTIvMzM1NzY0OTc5LTEwMTI5NmU5LTFlZTktNGJjZC1hNDA0LWUwNDBiZTNjYWMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMjEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjgyMTg1ZTk5NjE5OTIwNGJjMDc0YTRhNmEzMGEzZWY0M2QzMGQzODA4NmQ0OWY3OGVlNzhiNTFhZDZhOTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Md_zFmYZM__xD6mVNzOHheXKUXxFFqQjmaQLSA3eGEo) ![gpi2](https://private-user-images.githubusercontent.com/161665412/335765075-0a436cab-0014-4892-8dc6-e8819feed5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjg5NDAsIm5iZiI6MTczMjA2ODY0MCwicGF0aCI6Ii8xNjE2NjU0MTIvMzM1NzY1MDc1LTBhNDM2Y2FiLTAwMTQtNDg5Mi04ZGM2LWU4ODE5ZmVlZDVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMjEwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTAxMjk1ZjczMTIyNmJlN2YxYmM4YjNkNWE2MTBlOGQ1ODIwZDVjZmUyYmU2YTFmNDBlZDIwZTUyY2MxOGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qLjkvIsyGIrhrncU_P95JJq1_9EOjP0AiiYK3Y-TmGs)

same problem, any solution?
