### ISSUE TITLE
Is there a server-client mode?

### ISSUE THREAD

**Issue by RockyLOMO** [Const-me/Whisper#98]
Is there a server-client mode?  thanks.

**Comment by emcodem** [comment]
Well the output of a speech-to-text engine is text. How would you like to "serve" this text and what should a client do with it?

**Comment by Const-me** [comment]
@RockyLOMO No web or client-server is implemented.
The main project in this repository builds a Win64 DLL. Other projects build Windows desktop program, command-line program, and PowerShell module.
